[package]
name = "rust-string-matching"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]

[dependencies]
ocl = "~0.11"
time = "~0.1"
clap = "~2.18"
num = "~0.1"
rand="~0.3"
